### ISSUE TITLE
TF tree broken

### ISSUE THREAD

**Issue by bbrieber** [tu-darmstadt-ros-pkg/hector_quadrotor#11] opened 2014-07-09 11:38 UTC
when I use the  hector_quadrotor packages in hydro with gazebo the TF tree seems to be broken.
There is no connection between the base_link and base_stabilized.

I tried the current source from github and the debian packages which both seem to show the same behaviour

The broken tree makes all sensor unusable 
The problem could be reproduced on other PC too

**Comment by meyerj** [comment] 2014-07-09 11:45
Hi @bbrieber,

the broken tf tree has been observed before and was caused by an update in the message_to_tf package in [hector_localization](https://github.com/tu-darmstadt-ros-pkg/hector_localization) which translates the ground truth state from gazebo (`nav_msgs/Odometry`) into tf. The bug has been fixed in https://github.com/tu-darmstadt-ros-pkg/hector_localization/commit/83a695cf6d39fb6fef5ce0d70584d2d5774c02e5.

I will release a new version of hector_localization during the afternoon. Until the version is available in the public repos you have to compile hector_localization from source. Sorry for the inconvenience.

**Comment by meyerj** [comment] 2014-07-09 12:05
Release is pending: https://github.com/ros/rosdistro/pull/4969

**Closed as completed by meyerj** 2014-07-09 12:05 UTC

**Comment by bbrieber** [comment] 2014-07-09 12:39
thx for the quick answer

tested it and everything works fine again
